services:
  php-server:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_online_store_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d


volumes:
  pg_online_store_data:
